sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker

install:
  # install deps
  - yarn install

script:
  - yarn build
  # build docker images
  - docker build -t pederyodock/travis-ci-react-static .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
